server:
  port: 9010

spring:
  application:
    name: eureka-server

eureka:
  client:
    service-url:
      #eureka 服务地址，如果是集群的话；需要指定其他集群eureka地址
      defaultZone: http://127.0.0.1:9010/eureka
      # 不注册自己
    registry-with-eureka: false
    #不拉服务
    fetch-registry: false